version: '3.3'

services:
  backend:
    container_name: communication-service
    build:
      context: .
    ports:
      - '8082:8082'
    networks:
      - shared_network

networks:
  shared_network:
    external: true
