version: '3.3'

services:
  backend:
    container_name: communication-service
    build:
      context: .
    depends_on:
      - database
    restart: always
    ports:
      - '8082:8082'
    networks:
      - shared_network
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5432/config-db"
      SPRING_DATASOURCE_USERNAME: "user"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  database:
    container_name: comm-db
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: 'config-db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root-pass'
    ports:
      - '5434:5432'
    expose:
      - '5432'
    volumes:
      - config-db:/var/lib/postgresql/data
    networks:
      - shared_network

volumes:
  config-db:

networks:
  shared_network:
    external: true
